### ISSUE TITLE
BSQ tx confirmation count is wrong

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq-core#6]
When sending a BSQ transaction the confirmation counts double after restarting the client. The receiver doesn't count double.

See highlighted transaction after two blocks. For Bob it indicates 3 transactions but for Charlie only 2. 

![image](https://user-images.githubusercontent.com/23560607/37494820-cfa3d70c-28aa-11e8-8ced-da72d1eb4415.png)
![image](https://user-images.githubusercontent.com/23560607/37494825-d779f664-28aa-11e8-9c09-8e2cb85fce26.png)

**Comment by ManfredKarrer** [comment]
The sender has the tx in the BTC and the BSQ wallet because he pays the tx fee in BTC. The confidence gets incremented then twice from both wallets. 

In the Wallet.notifyNewBestBlock method we know the block height and we could use that to compare with TransactionConfidence.appearedAtChainHeight to calculate the correct depth.
So instead of calling the TransactionConfidence.incrementDepthInBlocks method rather call TransactionConfidence.setDepth with block.getHeight() - TransactionConfidence.getAppearedAtChainHeight().

Would require a bit more analysis if it would have any other usage/effect in BitcoinJ but what I have seen so far it should be feasible.

**Comment by sqrrm** [comment]
Fixed in https://github.com/bisq-network/bitcoinj/pull/12
